name: beldinuts

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beldinuts_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - beldinuts-network
      - shared_wobz_network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: beldinuts_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - beldinuts-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: beldinuts_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - beldinuts-network

networks:
  beldinuts-network:
    driver: bridge
  shared_wobz_network:
    external: true

